version: '3.9'

networks:
  www_default:
    external: true

services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./www:/var/www/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - www_default

  php-fpm:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./www:/var/www/
    networks:
      - www_default

  mysql:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: brak
      MARIADB_DATABASE: prawojazdy
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
    networks:
      - www_default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - www_default